"""Create Email Table

Revision ID: 032a4a0205a1
Revises: 
Create Date: 2021-11-13 01:22:35.837313

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '032a4a0205a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.Enum('ESTIMATION', 'AS', 'ETC', name='emailcategory'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('company', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=False),
    sa.Column('phone', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    # ### end Alembic commands ###
