"""Refactor Email Table to QNA

Revision ID: df5455e463fd
Revises: 032a4a0205a1
Create Date: 2021-11-13 21:59:47.077546

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df5455e463fd'
down_revision = '032a4a0205a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qnas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.Enum('ESTIMATION', 'AS', 'ETC', name='qnacategory'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('company', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=False),
    sa.Column('phone', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('emails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.ENUM('ESTIMATION', 'AS', 'ETC', name='emailcategory'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='emails_pkey')
    )
    op.drop_table('qnas')
    # ### end Alembic commands ###
